export const PROVIDERS_CONSTANTS = {
  SEQUELIZE: 'SEQUELIZE',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  PARKING_SPOTS_REPOSITORY: 'PARKING_SPOTS_REPOSITORY',
  RESERVATIONS_REPOSITORY: 'RESERVATIONS_REPOSITORY',
};
